/**
 * Image Optimization Script
 * - Converts PNG to WebP
 * - Resizes to max 1600px width
 * - Ensures output is under 600KB
 * - Generates blur placeholder data URLs (20px wide, base64)
 */
import sharp from 'sharp';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const IMAGES_DIR = path.join(__dirname, '..', 'images');
const MAX_WIDTH = 1600;
const MAX_FILE_SIZE = 600 * 1024; // 600KB
const BLUR_WIDTH = 20; // tiny placeholder

async function optimizeImage(filePath) {
  const ext = path.extname(filePath).toLowerCase();
  if (ext !== '.png') return null;

  const baseName = path.basename(filePath, ext);
  const outputPath = path.join(IMAGES_DIR, `${baseName}.webp`);

  console.log(`\nProcessing: ${baseName}.png`);

  // Get original metadata (allow huge images)
  const metadata = await sharp(filePath, { limitInputPixels: false }).metadata();
  console.log(`  Original: ${metadata.width}x${metadata.height}, ${(fs.statSync(filePath).size / 1024 / 1024).toFixed(2)}MB`);

  // Resize if wider than MAX_WIDTH, convert to WebP
  let quality = 82;
  let resizeOptions = {};
  if (metadata.width > MAX_WIDTH) {
    resizeOptions = { width: MAX_WIDTH, withoutEnlargement: true };
  }

  // Try progressively lower quality until under 600KB
  let outputBuffer;
  while (quality >= 30) {
    outputBuffer = await sharp(filePath, { limitInputPixels: false })
      .resize(resizeOptions)
      .webp({ quality, effort: 6 })
      .toBuffer();

    if (outputBuffer.length <= MAX_FILE_SIZE) break;
    console.log(`  Quality ${quality}: ${(outputBuffer.length / 1024).toFixed(0)}KB > 600KB, reducing...`);
    quality -= 5;
  }

  fs.writeFileSync(outputPath, outputBuffer);
  const finalSize = outputBuffer.length;
  console.log(`  Output: ${baseName}.webp, quality=${quality}, ${(finalSize / 1024).toFixed(0)}KB`);

  // Generate blur placeholder (tiny base64 image)
  const blurBuffer = await sharp(filePath, { limitInputPixels: false })
    .resize({ width: BLUR_WIDTH })
    .webp({ quality: 20 })
    .toBuffer();
  const blurDataUrl = `data:image/webp;base64,${blurBuffer.toString('base64')}`;
  console.log(`  Blur placeholder: ${blurBuffer.length} bytes`);

  return {
    name: baseName,
    originalSize: fs.statSync(filePath).size,
    optimizedSize: finalSize,
    blurDataUrl,
  };
}

async function main() {
  const files = fs.readdirSync(IMAGES_DIR).filter(f => f.toLowerCase().endsWith('.png'));
  console.log(`Found ${files.length} PNG files to optimize.\n`);

  const results = [];
  for (const file of files) {
    const result = await optimizeImage(path.join(IMAGES_DIR, file));
    if (result) results.push(result);
  }

  // Write blur placeholders to a JSON file for use in code
  const placeholders = {};
  for (const r of results) {
    placeholders[r.name] = r.blurDataUrl;
  }
  const placeholdersPath = path.join(__dirname, '..', 'src', 'data', 'image-placeholders.ts');
  const tsContent = `// Auto-generated blur placeholders — do not edit manually
// Generated by scripts/optimize-images.mjs

export const blurPlaceholders: Record<string, string> = ${JSON.stringify(placeholders, null, 2)};
`;
  fs.writeFileSync(placeholdersPath, tsContent);
  console.log(`\nWrote blur placeholders to src/data/image-placeholders.ts`);

  // Summary
  console.log('\n=== OPTIMIZATION SUMMARY ===');
  let totalOriginal = 0, totalOptimized = 0;
  for (const r of results) {
    const savings = ((1 - r.optimizedSize / r.originalSize) * 100).toFixed(1);
    console.log(`  ${r.name}: ${(r.originalSize / 1024 / 1024).toFixed(2)}MB → ${(r.optimizedSize / 1024).toFixed(0)}KB (${savings}% saved)`);
    totalOriginal += r.originalSize;
    totalOptimized += r.optimizedSize;
  }
  const totalSavings = ((1 - totalOptimized / totalOriginal) * 100).toFixed(1);
  console.log(`\n  TOTAL: ${(totalOriginal / 1024 / 1024).toFixed(2)}MB → ${(totalOptimized / 1024 / 1024).toFixed(2)}MB (${totalSavings}% saved)`);

  // Check all under 600KB
  const overLimit = results.filter(r => r.optimizedSize > MAX_FILE_SIZE);
  if (overLimit.length > 0) {
    console.log('\n⚠️  WARNING: These images exceed 600KB:');
    for (const r of overLimit) {
      console.log(`  ${r.name}: ${(r.optimizedSize / 1024).toFixed(0)}KB`);
    }
  } else {
    console.log('\n✅ All images are under 600KB!');
  }
}

main().catch(console.error);
